# Generated by Django 4.2.23 on 2025-06-29 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "asin",
                    models.CharField(
                        db_index=True, max_length=20, unique=True, verbose_name="ASIN"
                    ),
                ),
                (
                    "product_name",
                    models.CharField(max_length=255, verbose_name="Product Name"),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=100,
                        null=True,
                        verbose_name="Category",
                    ),
                ),
                (
                    "avg_selling_price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Average Selling Price",
                    ),
                ),
                (
                    "cost_of_goods_sold",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Cost of Goods Sold",
                    ),
                ),
                (
                    "initial_cvr_baseline",
                    models.FloatField(
                        help_text="Base conversion rate, e.g., 0.05 for 5%",
                        verbose_name="Initial CVR Baseline",
                    ),
                ),
                (
                    "initial_bestseller_rank",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Initial Bestseller Rank"
                    ),
                ),
                (
                    "review_count",
                    models.PositiveIntegerField(default=0, verbose_name="Review Count"),
                ),
                (
                    "avg_star_rating",
                    models.FloatField(
                        blank=True,
                        help_text="Average customer review star rating, e.g., 4.5",
                        null=True,
                        verbose_name="Average Star Rating",
                    ),
                ),
                (
                    "seasonality_profile",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("evergreen", "Evergreen Staple"),
                            ("seasonal_toy", "Seasonal Toy"),
                            ("seasonal_clothing", "Seasonal Clothing"),
                            ("other", "Other"),
                        ],
                        default="evergreen",
                        max_length=50,
                        null=True,
                        verbose_name="Seasonality Profile",
                    ),
                ),
                (
                    "competitive_intensity",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                        ],
                        default="medium",
                        max_length=50,
                        null=True,
                        verbose_name="Competitive Intensity",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Product",
                "verbose_name_plural": "Products",
                "ordering": ["product_name"],
            },
        ),
    ]
