"""add_campaign_adgroup_keyword_tables

Revision ID: 0c769b09dba8
Revises: 6ef96c9b8d21
Create Date: 2025-06-29 01:58:43.318925

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c769b09dba8'
down_revision: Union[str, Sequence[str], None] = '6ef96c9b8d21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaigns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('campaign_name', sa.String(), nullable=False),
    sa.Column('ad_type', sa.Enum('SPONSORED_PRODUCTS', 'SPONSORED_BRANDS', 'SPONSORED_DISPLAY', name='adtypeenum'), nullable=False),
    sa.Column('daily_budget', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('bidding_strategy', sa.Enum('DYNAMIC_DOWN_ONLY', 'DYNAMIC_UP_DOWN', 'FIXED_BIDS', name='biddingstrategyenum'), nullable=False),
    sa.Column('targeting_type', sa.Enum('AUTO', 'MANUAL', name='campaigntargetingtypeenum'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaigns_campaign_name'), 'campaigns', ['campaign_name'], unique=False)
    op.create_index(op.f('ix_campaigns_id'), 'campaigns', ['id'], unique=False)
    op.create_table('ad_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('ad_group_name', sa.String(), nullable=False),
    sa.Column('default_bid', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ad_groups_ad_group_name'), 'ad_groups', ['ad_group_name'], unique=False)
    op.create_index(op.f('ix_ad_groups_id'), 'ad_groups', ['id'], unique=False)
    op.create_table('keywords',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ad_group_id', sa.Integer(), nullable=False),
    sa.Column('keyword_text', sa.String(), nullable=False),
    sa.Column('match_type', sa.Enum('BROAD', 'PHRASE', 'EXACT', name='matchtypeenum'), nullable=False),
    sa.Column('bid', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.Enum('ENABLED', 'PAUSED', 'ARCHIVED', name='keywordstatusenum'), nullable=False),
    sa.ForeignKeyConstraint(['ad_group_id'], ['ad_groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_keywords_id'), 'keywords', ['id'], unique=False)
    op.create_index(op.f('ix_keywords_keyword_text'), 'keywords', ['keyword_text'], unique=False)

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('avg_selling_price',
                   existing_type=sa.FLOAT(),
                   type_=sa.Numeric(precision=10, scale=2),
                   existing_nullable=False)
        batch_op.alter_column('cost_of_goods_sold',
                   existing_type=sa.FLOAT(),
                   type_=sa.Numeric(precision=10, scale=2),
                   existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('cost_of_goods_sold',
                   existing_type=sa.Numeric(precision=10, scale=2),
                   type_=sa.FLOAT(),
                   existing_nullable=False)
        batch_op.alter_column('avg_selling_price',
                   existing_type=sa.Numeric(precision=10, scale=2),
                   type_=sa.FLOAT(),
                   existing_nullable=False)

    op.drop_index(op.f('ix_keywords_keyword_text'), table_name='keywords')
    op.drop_index(op.f('ix_keywords_id'), table_name='keywords')
    op.drop_table('keywords')
    op.drop_index(op.f('ix_ad_groups_id'), table_name='ad_groups')
    op.drop_index(op.f('ix_ad_groups_ad_group_name'), table_name='ad_groups')
    op.drop_table('ad_groups')
    op.drop_index(op.f('ix_campaigns_id'), table_name='campaigns')
    op.drop_index(op.f('ix_campaigns_campaign_name'), table_name='campaigns')
    op.drop_table('campaigns')
    # ### end Alembic commands ###
