"""add_negative_product_target_table

Revision ID: 4101e5542908
Revises: a8eaf6e6ff63
Create Date: 2025-06-29 02:46:54.528474

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4101e5542908'
down_revision: Union[str, Sequence[str], None] = 'a8eaf6e6ff63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('negative_product_targets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('target_asin', sa.String(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=True),
    sa.Column('ad_group_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('ENABLED', 'PAUSED', 'ARCHIVED', name='keywordstatusenum'), nullable=False),
    sa.CheckConstraint('(campaign_id IS NOT NULL AND ad_group_id IS NULL) OR (campaign_id IS NULL AND ad_group_id IS NOT NULL)', name='chk_negative_product_target_scope'),
    sa.ForeignKeyConstraint(['ad_group_id'], ['ad_groups.id'], ),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('negative_product_targets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_negative_product_targets_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_negative_product_targets_target_asin'), ['target_asin'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('negative_product_targets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_negative_product_targets_target_asin'))
        batch_op.drop_index(batch_op.f('ix_negative_product_targets_id'))

    op.drop_table('negative_product_targets')
    # ### end Alembic commands ###
