"""add_product_target_table

Revision ID: 86f2edad553e
Revises: 89129ce94b82
Create Date: 2025-06-29 02:32:01.868921

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86f2edad553e'
down_revision: Union[str, Sequence[str], None] = '89129ce94b82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_targets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ad_group_id', sa.Integer(), nullable=False),
    sa.Column('targeting_type', sa.Enum('ASIN_SAME_AS', 'CATEGORY_SAME_AS', name='producttargetingtypeenum'), nullable=False),
    sa.Column('target_value', sa.String(), nullable=False),
    sa.Column('bid', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('status', sa.Enum('ENABLED', 'PAUSED', 'ARCHIVED', name='producttargetstatusenum'), nullable=False),
    sa.ForeignKeyConstraint(['ad_group_id'], ['ad_groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('product_targets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_targets_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_targets_target_value'), ['target_value'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_targets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_targets_target_value'))
        batch_op.drop_index(batch_op.f('ix_product_targets_id'))

    op.drop_table('product_targets')
    # ### end Alembic commands ###
