"""add_product_target_link_to_ad_performance_metric

Revision ID: 9335d4ff3c8b
Revises: 4101e5542908
Create Date: 2025-06-29 02:53:25.385153

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9335d4ff3c8b'
down_revision: Union[str, Sequence[str], None] = '4101e5542908'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ad_performance_metrics', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_target_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_ad_performance_metrics_product_target_id'), ['product_target_id'], unique=False)
        batch_op.create_foreign_key('fk_ad_performance_metrics_product_target_id_product_targets',
                                   'product_targets', ['product_target_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ad_performance_metrics', schema=None) as batch_op:
        batch_op.drop_constraint('fk_ad_performance_metrics_product_target_id_product_targets', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_ad_performance_metrics_product_target_id'))
        batch_op.drop_column('product_target_id')

    # ### end Alembic commands ###
