"""add_negative_keyword_table

Revision ID: a8eaf6e6ff63
Revises: 86f2edad553e
Create Date: 2025-06-29 02:41:04.422317

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8eaf6e6ff63'
down_revision: Union[str, Sequence[str], None] = '86f2edad553e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('negative_keywords',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('keyword_text', sa.String(), nullable=False),
    sa.Column('match_type', sa.Enum('NEGATIVE_EXACT', 'NEGATIVE_PHRASE', name='negativematchtypeenum'), nullable=False),
    sa.Column('status', sa.Enum('ENABLED', 'PAUSED', 'ARCHIVED', name='keywordstatusenum'), nullable=False),
    sa.Column('ad_group_id', sa.Integer(), nullable=True),
    sa.CheckConstraint('(campaign_id IS NOT NULL AND ad_group_id IS NULL) OR (campaign_id IS NULL AND ad_group_id IS NOT NULL)', name='chk_negative_keyword_scope'),
    sa.ForeignKeyConstraint(['ad_group_id'], ['ad_groups.id'], ),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('negative_keywords', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_negative_keywords_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_negative_keywords_keyword_text'), ['keyword_text'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('negative_keywords', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_negative_keywords_keyword_text'))
        batch_op.drop_index(batch_op.f('ix_negative_keywords_id'))

    op.drop_table('negative_keywords')
    # ### end Alembic commands ###
