"""add_adperformancemetric_and_searchtermperformance_tables

Revision ID: daa78da7cfb6
Revises: 0c769b09dba8
Create Date: 2025-06-29 02:04:43.787164

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'daa78da7cfb6'
down_revision: Union[str, Sequence[str], None] = '0c769b09dba8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ad_performance_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('metric_date', sa.Date(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('ad_group_id', sa.Integer(), nullable=True),
    sa.Column('keyword_id', sa.Integer(), nullable=True),
    sa.Column('placement', sa.Enum('TOP_OF_SEARCH', 'PRODUCT_PAGE', 'REST_OF_SEARCH', 'UNKNOWN', name='placementenum'), nullable=True),
    sa.Column('impressions', sa.Integer(), nullable=True),
    sa.Column('clicks', sa.Integer(), nullable=True),
    sa.Column('spend', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('orders', sa.Integer(), nullable=True),
    sa.Column('sales', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('acos', sa.Float(), nullable=True),
    sa.Column('roas', sa.Float(), nullable=True),
    sa.Column('cpc', sa.Float(), nullable=True),
    sa.Column('ctr', sa.Float(), nullable=True),
    sa.Column('cvr', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['ad_group_id'], ['ad_groups.id'], ),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['keyword_id'], ['keywords.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ad_performance_metrics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ad_performance_metrics_ad_group_id'), ['ad_group_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ad_performance_metrics_campaign_id'), ['campaign_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ad_performance_metrics_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ad_performance_metrics_keyword_id'), ['keyword_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ad_performance_metrics_metric_date'), ['metric_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_ad_performance_metrics_user_id'), ['user_id'], unique=False)

    op.create_table('search_terms_performance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('search_term_text', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('ad_group_id', sa.Integer(), nullable=False),
    sa.Column('matched_keyword_id', sa.Integer(), nullable=True),
    sa.Column('impressions', sa.Integer(), nullable=True),
    sa.Column('clicks', sa.Integer(), nullable=True),
    sa.Column('spend', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('orders', sa.Integer(), nullable=True),
    sa.Column('sales', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('acos', sa.Float(), nullable=True),
    sa.Column('roas', sa.Float(), nullable=True),
    sa.Column('cpc', sa.Float(), nullable=True),
    sa.Column('ctr', sa.Float(), nullable=True),
    sa.Column('cvr', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['ad_group_id'], ['ad_groups.id'], ),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['matched_keyword_id'], ['keywords.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('search_terms_performance', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_search_terms_performance_ad_group_id'), ['ad_group_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_search_terms_performance_campaign_id'), ['campaign_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_search_terms_performance_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_search_terms_performance_matched_keyword_id'), ['matched_keyword_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_search_terms_performance_report_date'), ['report_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_search_terms_performance_search_term_text'), ['search_term_text'], unique=False)
        batch_op.create_index(batch_op.f('ix_search_terms_performance_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('search_terms_performance', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_search_terms_performance_user_id'))
        batch_op.drop_index(batch_op.f('ix_search_terms_performance_search_term_text'))
        batch_op.drop_index(batch_op.f('ix_search_terms_performance_report_date'))
        batch_op.drop_index(batch_op.f('ix_search_terms_performance_matched_keyword_id'))
        batch_op.drop_index(batch_op.f('ix_search_terms_performance_id'))
        batch_op.drop_index(batch_op.f('ix_search_terms_performance_campaign_id'))
        batch_op.drop_index(batch_op.f('ix_search_terms_performance_ad_group_id'))

    op.drop_table('search_terms_performance')
    with op.batch_alter_table('ad_performance_metrics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ad_performance_metrics_user_id'))
        batch_op.drop_index(batch_op.f('ix_ad_performance_metrics_metric_date'))
        batch_op.drop_index(batch_op.f('ix_ad_performance_metrics_keyword_id'))
        batch_op.drop_index(batch_op.f('ix_ad_performance_metrics_id'))
        batch_op.drop_index(batch_op.f('ix_ad_performance_metrics_campaign_id'))
        batch_op.drop_index(batch_op.f('ix_ad_performance_metrics_ad_group_id'))

    op.drop_table('ad_performance_metrics')
    # ### end Alembic commands ###
