# Generated by Django 4.2.23 on 2025-06-29 05:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.functions.datetime


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True, max_length=255, verbose_name="Ad Group Name"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("enabled", "Enabled"),
                            ("paused", "Paused"),
                            ("archived", "Archived"),
                        ],
                        default="enabled",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "default_bid",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Default bid for keywords/targets in this ad group if their specific bid is not set.",
                        max_digits=10,
                        null=True,
                        verbose_name="Default Bid",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Ad Group",
                "verbose_name_plural": "Ad Groups",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Campaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True, max_length=255, verbose_name="Campaign Name"
                    ),
                ),
                (
                    "ad_type",
                    models.CharField(
                        choices=[("sponsored_products", "Sponsored Products")],
                        default="sponsored_products",
                        max_length=50,
                        verbose_name="Ad Type",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("enabled", "Enabled"),
                            ("paused", "Paused"),
                            ("archived", "Archived"),
                        ],
                        default="enabled",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "daily_budget",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Daily Budget"
                    ),
                ),
                (
                    "start_date",
                    models.DateField(
                        default=django.db.models.functions.datetime.Now,
                        verbose_name="Start Date",
                    ),
                ),
                (
                    "end_date",
                    models.DateField(blank=True, null=True, verbose_name="End Date"),
                ),
                (
                    "bidding_strategy",
                    models.CharField(
                        choices=[
                            ("dynamic_bids_down_only", "Dynamic bids - down only"),
                            ("dynamic_bids_up_and_down", "Dynamic bids - up and down"),
                            ("fixed_bids", "Fixed bids"),
                        ],
                        default="dynamic_bids_down_only",
                        max_length=50,
                        verbose_name="Bidding Strategy",
                    ),
                ),
                (
                    "targeting_type",
                    models.CharField(
                        blank=True,
                        choices=[("manual", "Manual"), ("auto", "Automatic")],
                        max_length=20,
                        null=True,
                        verbose_name="Targeting Type",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Campaign",
                "verbose_name_plural": "Campaigns",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="NegativeProductTarget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "target_asin",
                    models.CharField(
                        db_index=True, max_length=20, verbose_name="Target ASIN"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("enabled", "Enabled"),
                            ("paused", "Paused"),
                            ("archived", "Archived"),
                        ],
                        default="enabled",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "ad_group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="negative_product_targets",
                        to="campaigns.adgroup",
                    ),
                ),
                (
                    "campaign",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="negative_product_targets",
                        to="campaigns.campaign",
                    ),
                ),
            ],
            options={
                "verbose_name": "Negative Product Target",
                "verbose_name_plural": "Negative Product Targets",
            },
        ),
        migrations.CreateModel(
            name="NegativeKeyword",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "keyword_text",
                    models.CharField(
                        db_index=True,
                        max_length=255,
                        verbose_name="Negative Keyword Text",
                    ),
                ),
                (
                    "match_type",
                    models.CharField(
                        choices=[
                            ("negative_exact", "Negative Exact"),
                            ("negative_phrase", "Negative Phrase"),
                        ],
                        max_length=50,
                        verbose_name="Match Type",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("enabled", "Enabled"),
                            ("paused", "Paused"),
                            ("archived", "Archived"),
                        ],
                        default="enabled",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "ad_group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="negative_keywords",
                        to="campaigns.adgroup",
                    ),
                ),
                (
                    "campaign",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="negative_keywords",
                        to="campaigns.campaign",
                    ),
                ),
            ],
            options={
                "verbose_name": "Negative Keyword",
                "verbose_name_plural": "Negative Keywords",
            },
        ),
        migrations.CreateModel(
            name="CampaignProductLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="campaigns.campaign",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Campaign-Product Link",
                "verbose_name_plural": "Campaign-Product Links",
                "unique_together": {("campaign", "product")},
            },
        ),
        migrations.AddField(
            model_name="campaign",
            name="advertised_products",
            field=models.ManyToManyField(
                blank=True,
                related_name="campaigns_featuring_product",
                through="campaigns.CampaignProductLink",
                to="products.product",
            ),
        ),
        migrations.AddField(
            model_name="campaign",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="campaigns",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="adgroup",
            name="campaign",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ad_groups",
                to="campaigns.campaign",
            ),
        ),
        migrations.CreateModel(
            name="ProductTarget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "targeting_type",
                    models.CharField(
                        choices=[
                            ("asin_same_as", "ASIN"),
                            ("category_same_as", "Category"),
                        ],
                        max_length=50,
                        verbose_name="Targeting Type",
                    ),
                ),
                (
                    "target_value",
                    models.CharField(
                        db_index=True, max_length=255, verbose_name="Target Value"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("enabled", "Enabled"),
                            ("paused", "Paused"),
                            ("archived", "Archived"),
                        ],
                        default="enabled",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "bid",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Optional: Overrides ad group default bid.",
                        max_digits=10,
                        null=True,
                        verbose_name="Bid",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "ad_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_targets",
                        to="campaigns.adgroup",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product Target",
                "verbose_name_plural": "Product Targets",
                "unique_together": {("ad_group", "targeting_type", "target_value")},
            },
        ),
        migrations.CreateModel(
            name="Keyword",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "text",
                    models.CharField(
                        db_index=True, max_length=255, verbose_name="Keyword Text"
                    ),
                ),
                (
                    "match_type",
                    models.CharField(
                        choices=[
                            ("broad", "Broad"),
                            ("phrase", "Phrase"),
                            ("exact", "Exact"),
                        ],
                        max_length=20,
                        verbose_name="Match Type",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("enabled", "Enabled"),
                            ("paused", "Paused"),
                            ("archived", "Archived"),
                        ],
                        default="enabled",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "bid",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Bid"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "ad_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="keywords",
                        to="campaigns.adgroup",
                    ),
                ),
            ],
            options={
                "verbose_name": "Keyword",
                "verbose_name_plural": "Keywords",
                "unique_together": {("ad_group", "text", "match_type")},
            },
        ),
    ]
