# Generated by Django 4.2.23 on 2025-06-29 11:19

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("campaigns", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SearchTermPerformance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "report_date",
                    models.DateField(db_index=True, verbose_name="Report Date"),
                ),
                (
                    "search_term_text",
                    models.CharField(
                        db_index=True, max_length=255, verbose_name="Search Term"
                    ),
                ),
                (
                    "impressions",
                    models.PositiveIntegerField(default=0, verbose_name="Impressions"),
                ),
                (
                    "clicks",
                    models.PositiveIntegerField(default=0, verbose_name="Clicks"),
                ),
                (
                    "spend",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        verbose_name="Spend",
                    ),
                ),
                (
                    "orders",
                    models.PositiveIntegerField(default=0, verbose_name="Orders"),
                ),
                (
                    "sales",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Sales",
                    ),
                ),
                (
                    "acos",
                    models.FloatField(
                        default=0.0, editable=False, verbose_name="ACoS (%)"
                    ),
                ),
                (
                    "roas",
                    models.FloatField(default=0.0, editable=False, verbose_name="ROAS"),
                ),
                (
                    "cpc",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        editable=False,
                        max_digits=10,
                        verbose_name="CPC",
                    ),
                ),
                (
                    "ctr",
                    models.FloatField(
                        default=0.0, editable=False, verbose_name="CTR (%)"
                    ),
                ),
                (
                    "cvr",
                    models.FloatField(
                        default=0.0, editable=False, verbose_name="CVR (%)"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "ad_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="search_term_performance_data",
                        to="campaigns.adgroup",
                    ),
                ),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="search_term_performance_data",
                        to="campaigns.campaign",
                    ),
                ),
                (
                    "matched_keyword",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="matched_search_term_data",
                        to="campaigns.keyword",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="search_term_performance_data",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Search Term Performance",
                "verbose_name_plural": "Search Term Performances",
                "ordering": ["-report_date", "search_term_text"],
            },
        ),
        migrations.CreateModel(
            name="AdPerformanceMetric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "metric_date",
                    models.DateField(db_index=True, verbose_name="Metric Date"),
                ),
                (
                    "placement",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("top_of_search", "Top of Search"),
                            ("product_page", "Product Page"),
                            ("rest_of_search", "Rest of Search"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=50,
                        null=True,
                        verbose_name="Placement",
                    ),
                ),
                (
                    "impressions",
                    models.PositiveIntegerField(default=0, verbose_name="Impressions"),
                ),
                (
                    "clicks",
                    models.PositiveIntegerField(default=0, verbose_name="Clicks"),
                ),
                (
                    "spend",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        verbose_name="Spend",
                    ),
                ),
                (
                    "orders",
                    models.PositiveIntegerField(default=0, verbose_name="Orders"),
                ),
                (
                    "sales",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Sales",
                    ),
                ),
                (
                    "acos",
                    models.FloatField(
                        default=0.0, editable=False, verbose_name="ACoS (%)"
                    ),
                ),
                (
                    "roas",
                    models.FloatField(default=0.0, editable=False, verbose_name="ROAS"),
                ),
                (
                    "cpc",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        editable=False,
                        max_digits=10,
                        verbose_name="CPC",
                    ),
                ),
                (
                    "ctr",
                    models.FloatField(
                        default=0.0, editable=False, verbose_name="CTR (%)"
                    ),
                ),
                (
                    "cvr",
                    models.FloatField(
                        default=0.0, editable=False, verbose_name="CVR (%)"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "ad_group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="performance_metrics_for_adgroup",
                        to="campaigns.adgroup",
                    ),
                ),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="performance_metrics_for_campaign",
                        to="campaigns.campaign",
                    ),
                ),
                (
                    "keyword",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="performance_metrics_for_keyword",
                        to="campaigns.keyword",
                    ),
                ),
                (
                    "product_target",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="performance_metrics_for_producttarget",
                        to="campaigns.producttarget",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ad_performance_metrics",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Ad Performance Metric",
                "verbose_name_plural": "Ad Performance Metrics",
                "ordering": ["-metric_date", "campaign", "ad_group"],
            },
        ),
        migrations.AddConstraint(
            model_name="adperformancemetric",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("keyword__isnull", False),
                    ("product_target__isnull", False),
                    _negated=True,
                ),
                name="chk_metric_single_target_type",
            ),
        ),
    ]
